# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d5b142e483fc4f680c4f6a619f0442fc9ad83af830a31e6a73cd0c34dc9c05414850525ccf72ac22fd0df4cb171afb0778e3d4035ed7e6e132ddd58875596a

test:
  secret_key_base: 988179177493c8aeed5167251857d8ba5048598861f3d9a128f42ee767e04b8293046034cd000b5a1affb14948832153622e5916b27b1ce0e4410190e5d89ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
